-- 字段联动计算
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('7', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.taxPrice', '含税单价', '0', 'ucf.customer.CusQuotation', 'taxPrice', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[valueTaxInLocal]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:02:53', NULL, '0');
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('8', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.taxFreeAmount', '无税金额', '0', 'ucf.customer.CusQuotation', 'taxFreeAmount', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[taxFreeAmount]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:02:58', NULL, '0');
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('9', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.taxAmount', '税额', '0', 'ucf.customer.CusQuotation', 'taxAmount', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[taxAmount]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:03:08', NULL, '0');
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('10', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.valueTaxTotal', '价税合计', '0', 'ucf.customer.CusQuotation', 'valueTaxTotal', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[valueTaxTotal]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:03:12', NULL, '0');
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('11', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.taxFreeInLocal', '本币无税金额', '0', 'ucf.customer.CusQuotation', 'taxFreeInLocal', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[taxFreeInLocal]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:03:16', NULL, '0');
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('12', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.taxInLocal', '本币税额', '0', 'ucf.customer.CusQuotation', 'taxInLocal', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[taxInLocal]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:03:20', NULL, '0');
INSERT INTO `bill_itemrule` (`id`, `billnumber`, `ruleid`, `rulename`, `ruletype`, `entity`, `item`, `defined`, `condition`, `expression`, `triggers`, `subid`, `system`, `pubts`, `sysid`, `tenant_id`) VALUES ('13', 'ucf_cus_quotation_card', 'ucf.cus_quotation_card.CusQuotationMateriel.valueTaxInLocal', '本币价税合计', '0', 'ucf.customer.CusQuotation', 'valueTaxInLocal', '0', NULL, 'sum<ucf.customer.CusQuotationMateriel>{[ucf.customer.CusQuotationMateriel].[valueTaxInLocal]*1}', '[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[valuationQuantity],[ucf.customer.CusQuotationMateriel].[taxFreePrice],[ucf.customer.CusQuotationMateriel].[taxRate],[ucf.customer.CusQuotationMateriel].[taxPrice],[ucf.customer.CusQuotationMateriel].[taxFreeAmount],[ucf.customer.CusQuotationMateriel].[taxAmount],[ucf.customer.CusQuotationMateriel].[valueTaxTotal]', 'UCF', '0', '2019-09-18 15:03:28', NULL, '0');

-- 编码规则(注意tenant_id的值,应该跟当前登陆测试账户的租户保持一致)
INSERT INTO `aa_billnumber` (`autoid`, `tenant_id`, `orgId`, `cbillnum`, `cbillname`, `csubid`, `ballowhandwork`, `brepeatredo`, `istartnumber`, `iseriallen`, `billnumLen`, `billnumInit`, `billnumTruncatType`, `billnumFillType`, `billnumFillMark`, `billnumMode`, `billnumRule`, `isReuse`, `sysid`, `datatype`, `rulecode`, `rulename`, `dr`, `pubts`, `yhtTenantId`, `sntype`) VALUES ('47', NULL, '-1', 'ucf_cus_quotation_card', 'mdf示例', NULL, '0', '1', '1', '8', '8', '1', '0', '1', '0', '1', '1', '0', 'diwork', '2', 'ucf_cus_quotation_card', NULL, '0', '2019-05-30 16:01:20', '0', '0');
INSERT INTO `aa_billnumber` (`autoid`, `tenant_id`, `orgId`, `cbillnum`, `cbillname`, `csubid`, `ballowhandwork`, `brepeatredo`, `istartnumber`, `iseriallen`, `billnumLen`, `billnumInit`, `billnumTruncatType`, `billnumFillType`, `billnumFillMark`, `billnumMode`, `billnumRule`, `isReuse`, `sysid`, `datatype`, `rulecode`, `rulename`, `dr`, `pubts`, `yhtTenantId`, `sntype`) VALUES ('48', NULL, '-1', 'ucf_cus_quotation_card', 'mdf示例', NULL, '0', '1', '1', '8', '8', '1', '0', '1', '0', '1', '1', '0', 'diwork', '2', 'ucf_cus_quotation_card', NULL, '0', '2019-05-30 16:01:20', 'gb0ucj8l', '0');

-- 价税合计
INSERT INTO `billruleregister` (  `billnum`, `action`, `ruleId`, `iorder`, `overrule`, `tenant_id`, `key`, `isSystem`, `url`, `isSync`, `isAsyn`, `config`) VALUES (  'common', 'check', 'extTaxCalculateRule', '30.00', NULL, '0', NULL, '', NULL, '0', '0', NULL);
-- 编码规则-后编码
INSERT INTO `billruleregister` ( `billnum`, `action`, `ruleId`, `iorder`, `overrule`, `tenant_id`, `key`, `isSystem`, `url`, `isSync`, `isAsyn`, `config`) VALUES ( 'common', 'save', 'mddUpdateBillCodeRule', '10.00', NULL, '0', NULL, '', NULL, '0', '0', NULL);
