export default {
  // defaultLang: '跟随系统（默认）',
  // zhsimp: '简体中文',
  // zhtr : '繁体',
    langSet: [
        {
            label: "跟随系统（默认）",
            value: "default",
        },
        {
            label: "简体中文",
            value: "zh-CN",
        },
        {
            label: "繁体中文",
            value: "zh-TW",
        },
    ],
    i18n: "多语言",
    set: "设置",
    i18nset: "多语言设置",
    clearnCatch: "清除本地缓存",
    logout: "退出登录",

    appDevelop: "应用开发",
    appPush: "新发布应用",
    appNum: "应用数量",
    setEnv: "配置环境",
    toDo: "待办通知",
    mtlerr:"无法使用，请检查插件是否正常",
    noticeList: "通知列表",
    about: "关于",

    work: "工作台",
    mine: "我的",

    noAppsAlt: "此应用暂未部署",
    getCodeErr: "获取esnCode失败",
    appName: "应用名称",
    buildApp: "所构建应用",
    noApp: "暂无应用",

    getCode: "获取验证码",
    codeLogin: "验证码登录",
    phoneNum: "手机号",
    email: "邮箱",
    code: "验证码",
    pwd: "密码",
    welcome: "欢迎",
    come: "来到",
    login: "登录",
    regionCode: "选择国家或地区",
    regionList: [
        {
            label: "中国",
            value: "+86",
        },
        {
            label: "中国香港",
            value: "+852",
        },
        {
            label: "中国澳门",
            value: "+853",
        },
        {
            label: "中国台湾",
            value: "+886",
        },
    ],

    envChange: "环境切换",
    manage: "管理",
    cancel: "取消",
    OK: "确定",
    del: "删除",
    daily: "yonBIP日常环境",
    pre: "yonBIP预发布环境",
    prod:'yonBIP生产环境',
    add: "新增环境",
    delOk: "确定要删此环境吗？",
    delOkLo: "确定清除本地缓存吗？",
    envInfo: "环境信息",
    save: "保存",
    inputLable: "请输入环境名称",
    inputUrl: "请输入URL",
    addFail: "与其他环境冲突，请重新输入",
    userName: "请输入账号",
    phoneNumberTips: "请输入正确的手机号",
    areLogOut: "确定退出？",
    loginerr: '登录错误，请检查账号密码',
    version: '版本',
    changing: '正在切换中',
    envnosave: '请先测试URL是否可用',
    envNoUse: '此环境暂不能用',
    testUrl: '测试链接',
    rightURL: "请输入正确的URL",
    envCanUse:'环境可用',
    testing:'测试中',
    changSuccess: '切换成功',
    checkVersion: '检查更新',
    otherLoginMode: '其他登录方式',
    register: '注册',
    forgetPwd: '忘记密码',
    remeberMe: '记住密码',
    phonePwdLogin: '友互通账号登录',//'手机密码登录',
    scanCodeLogin: '扫码登录',
    emailPwdLogin: '邮箱密码登录',
    codeTips: '请输入验证码',
    emailTips: "请输入正确的邮箱",
    nextStep: "下一步",
    realName: "真实姓名",
    realNameTips: "请输入真实姓名",
    registerTips: "8-12位数字、字母或符号",
    findPwd: "找回密码",
    findPwdList: [
        {
            label: "手机号码验证找回",
            title: "手机找回密码",
            value: "0"
        },
        {
            label: "邮箱找回",
            title: "邮箱找回密码",
            value: "1"
        },
    ],
    findPwdTips: "8-20位数字、字母或符号，不能设置最近5次使用的密码",
    complete: "完成",
    yonService: "《友空间服务协议》",
    cloudPrivacy: "《用友云隐私条款》",
    andClause: "和",
    tipAgreeMes: "点击下一步按钮，即表示您同意",
    codeFail: "验证码获取失败",
    writePlease: "请输入",
    nullTips: "不能为空",
    loading: "加载中",
    scanLoginNull: "扫码错误，请联系管理员",
    upgradeTips: "更新提示",
    newVersionTips: "发现新版本",
    newPwdTips: "输入新密码",
    pwdFormatErr: "密码格式错误",
    versionUpdateTips: "当前已是最新版本",
    abnormalNetInter: "网络接口异常"
};
