export default {
  // defaultLang: "跟隨系統（默認）",
  // zhsimp: "簡體中文",
  // zhtr: "繁體中文",
    langSet: [
        {
            label: "跟隨系統（默認）",
            value: "default",
        },
        {
            label: "簡體中文",
            value: "zh-CN",
        },
        {
            label: "繁體中文",
            value: "zh-TW",
        },
    ],
    i18n: "多語言",
    set: "設置",
    i18nset: "多語言設置",
    clearnCatch: "清除本地緩存",
    logout: "退出登錄",
    appDevelop: "應用開發",
    appPush: "新發佈應用",
    appNum: "應用數量",
    setEnv: "配置環境",
    toDo: "待辦通知",
    mtlerr:'無法使用，請檢查插件是否正常',
    noticeList: "通知列表",
    about: "關於",
    work: "工作臺",
    mine: "我的",
    noAppsAlt: "此應用暫未部署",
    getCodeErr: "獲取esnCode失敗",
    appName: "應用名稱",
    buildApp: "所構建應用",
    noApp: "暫無應用",
    getCode: "獲取驗證碼",
    codeLogin: "驗證碼登錄",
    phoneNum: "手機號",
    email: "郵箱",
    code: "驗證碼",
    pwd: "密碼",
    welcome: "歡迎",
    come: "來到",
    login: "登錄",
    regionCode: "選擇國家或地區",
    regionList: [
        {
            label: "中國",
            value: "+86",
        },
        {
            label: "中國香港",
            value: "+852",
        },
        {
            label: "中國澳門",
            value: "+853",
        },
        {
            label: "中國臺灣",
            value: "+886",
        },
    ],
    envChange: "環境切換",
    manage: "管理",
    cancel: "取消",
    OK: "確定",
    del: "刪除",
    daily: "yonBIP日常環境",
    pre: "yonBIP預發佈環境",
    prod:'yonBIP生產環境',
    add: "新增環境",
    delOk: "確定要刪除此環境嗎？",
    delOkLo: "確定清除本地緩存嗎？",
    envInfo: "環境資訊",
    save: "保存",
    inputLable: "請輸入環境名稱",
    inputUrl: "請輸入URL",
    addFail: "與其他環境衝突，請重新輸入",
    userName: "請輸入帳號",
    phoneNumberTips: "請輸入正確的手機號",
    // pwd: "請輸入密碼",
    areLogOut: "確定退出？",
    loginerr: '登錄錯誤，請檢查賬號密碼',
    version: '版本',
    changing:"正在切換中",
    envnosave: '请先测试URL是否可用',
    envNoUse: '此環境暫不能用',
    testUrl: '測試鏈接',
    rightURL: "請輸入正確的URL",
    envCanUse:'環境可用',
    testing:'測試中',
    changSuccess: '切換成功',
    checkVersion: '檢查更新',
    otherLoginMode: '其他登錄方式',
    register: '注冊',
    forgetPwd: '忘記密碼',
    remeberMe: '記住密碼',
    phonePwdLogin: '友互通賬號登錄',//'手機密碼登錄',
    scanCodeLogin: '掃碼登錄',
    emailPwdLogin: '郵箱密碼登錄',
    codeTips: '請輸入驗證碼',
    emailTips: "請輸入正確的郵箱",
    nextStep: "下一步",
    realName: "真實姓名",
    realNameTips: "請輸入真實姓名",
    registerTips: "8-12位數字、字母或符號",
    findPwd: "找回密碼",
    findPwdList: [
        {
            label: "手機號碼驗證找回",
            title: "手機找回密碼",
            value: "0"
        },
        {
            label: "郵箱找回",
            title: "郵箱找回密碼",
            value: "1"
        },
    ],
    findPwdTips: "8-20位數字、字母或符號，不能設置最近5次使用的密碼",
    complete: "完成",
    yonService: "《友空間服務協議》",
    cloudPrivacy: "《用友云隱私條款》",
    andClause: "和",
    tipAgreeMes: "點擊下一步按鈕，即表示您同意",
    codeFail: "驗證碼獲取失敗",
    writePlease: "請輸入",
    nullTips: "不能爲空",
    loading: "加載中",
    scanLoginNull: "掃碼錯誤，請聯係管理員",
    upgradeTips: "更新提示",
    newVersionTips: "發現新版本",
    newPwdTips: "輸入新密碼",
    pwdFormatErr: "密碼格式錯誤",
    versionUpdateTips: "當前已是最新版本",
    abnormalNetInter: "網絡接口異常"
};
